ANIMAIS = {
    "galinha": {
        "nome": "Galinha",
        "emoji": "🐔",
        "local": "galinheiro",
        "produto": "ovo",
        "produto_nome": "Ovos",
        "produto_emoji": "🥚",
        "tempo_produto_segundos": 20 * 60,
        "tempo_procriacao_segundos": 60 * 60,
        "consumo_racao_produto": 2,
        "consumo_racao_procriacao": 6,
        "preco_compra": 35,
        "valor_carne": 18,
    },
    "vaca": {
        "nome": "Vaca",
        "emoji": "🐄",
        "local": "celeiro",
        "produto": "leite_vaca",
        "produto_nome": "Leite de vaca",
        "produto_emoji": "🥛",
        "tempo_produto_segundos": 30 * 60,
        "tempo_procriacao_segundos": 60 * 60,
        "consumo_racao_produto": 5,
        "consumo_racao_procriacao": 14,
        "preco_compra": 120,
        "valor_carne": 90,
    },
    "ovelha": {
        "nome": "Ovelha",
        "emoji": "🐑",
        "local": "celeiro",
        "produto": "la",
        "produto_nome": "Lã",
        "produto_emoji": "🧶",
        "tempo_produto_segundos": 45 * 60,
        "tempo_procriacao_segundos": 60 * 60,
        "consumo_racao_produto": 4,
        "consumo_racao_procriacao": 10,
        "preco_compra": 90,
        "valor_carne": 55,
    },
    "cabra": {
        "nome": "Cabra",
        "emoji": "🐐",
        "local": "celeiro",
        "produto": "leite_cabra",
        "produto_nome": "Leite de cabra",
        "produto_emoji": "🥛",
        "tempo_produto_segundos": 35 * 60,
        "tempo_procriacao_segundos": 60 * 60,
        "consumo_racao_produto": 4,
        "consumo_racao_procriacao": 10,
        "preco_compra": 85,
        "valor_carne": 50,
    },
    "cavalo": {
        "nome": "Cavalo",
        "emoji": "🐎",
        "local": "estabulo",
        "produto": None,
        "produto_nome": None,
        "produto_emoji": None,
        "tempo_produto_segundos": None,
        "tempo_procriacao_segundos": 60 * 60,
        "consumo_racao_produto": 0,
        "consumo_racao_procriacao": 16,
        "preco_compra": 300,
        "valor_carne": 0,
    },
}

RACAO_MAXIMA = 100
RACAO_INICIAL = 50
CUSTO_ENTREGA_RACAO = 60
VALOR_ENTREGA_RACAO = 100
